# Generated by Django 5.0.2 on 2024-03-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypublish',
            name='photo',
        ),
    ]
