# Generated by Django 5.0.4 on 2024-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_mypublish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypublish',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
